version: '3'
services:
  web:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/code
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_USER: rmfadmin
      POSTGRES_PASSWORD: rmfpass
      POSTGRES_DB: rmfdb
    ports:
      - "5432:5432"
